/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;
import AppPackage.AnimationClass.*;

/**
 *
 * @author Muchwat
 */
public class MainClass extends javax.swing.JFrame {

    /**
     * Creates new form MainClass
     */
    public MainClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        idcard = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        prompt = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        submit = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        showpass = new javax.swing.JLabel();
        project = new javax.swing.JLabel();
        bymuchwat = new javax.swing.JLabel();
        show = new javax.swing.JCheckBox();
        Container = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(926, 615));
        setMinimumSize(new java.awt.Dimension(926, 615));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/exit.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 5, -1, -1));

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/logoe.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        idcard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idcard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/id.png"))); // NOI18N
        getContentPane().add(idcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 290, 170));

        Login.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(102, 102, 102));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 30));

        prompt.setForeground(new java.awt.Color(52, 68, 87));
        prompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(prompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, 20));

        username.setBackground(new java.awt.Color(11, 11, 11));
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(null);
        username.setSelectionColor(new java.awt.Color(52, 76, 100));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 413, 243, 33));

        password.setBackground(new java.awt.Color(11, 11, 11));
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(102, 102, 102));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(null);
        password.setSelectionColor(new java.awt.Color(52, 76, 100));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 455, 243, 33));

        submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/key.PNG"))); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 497, 272, 31));

        reset.setForeground(new java.awt.Color(102, 102, 102));
        reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset.setText("Reset inputs.");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        showpass.setForeground(new java.awt.Color(102, 102, 102));
        showpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showpass.setText("Show password");
        showpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        project.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        project.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/prjct1.png"))); // NOI18N
        project.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        project.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectMouseExited(evt);
            }
        });
        getContentPane().add(project, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 560, -1, -1));

        bymuchwat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bymuchwat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/muchu.png"))); // NOI18N
        getContentPane().add(bymuchwat, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, -1, -1));

        show.setBackground(new java.awt.Color(0, 51, 102));
        show.setForeground(new java.awt.Color(102, 102, 102));
        show.setBorder(null);
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.setFocusPainted(false);
        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        show.setIconTextGap(2);
        show.setMargin(new java.awt.Insets(0, 0, 0, 0));
        show.setMaximumSize(new java.awt.Dimension(8, 8));
        show.setMinimumSize(new java.awt.Dimension(8, 8));
        show.setOpaque(false);
        show.setPreferredSize(new java.awt.Dimension(8, 8));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 545, -1, -1));

        Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/bg-R.png"))); // NOI18N
        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 926, 615));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        ImageIcon a = new ImageIcon(getClass().getResource("/AppPackage/closef.png"));
        exit.setIcon(a);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        ImageIcon f = new ImageIcon(getClass().getResource("/AppPackage/exit.png"));
        exit.setIcon(f);
    }//GEN-LAST:event_exitMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("/AppPackage/minf.png"));
        min.setIcon(b);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        ImageIcon e = new ImageIcon(getClass().getResource("/AppPackage/min.png"));
        min.setIcon(e);
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
       this.setState(MainClass.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        ImageIcon c = new ImageIcon(getClass().getResource("/AppPackage/ky.png"));
        submit.setIcon(c);
    }//GEN-LAST:event_submitMouseEntered

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
       ImageIcon d = new ImageIcon(getClass().getResource("/AppPackage/key.PNG"));
        submit.setIcon(d);
       
    }//GEN-LAST:event_submitMouseExited

    private void projectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectMouseEntered
       ImageIcon e = new ImageIcon(getClass().getResource("/AppPackage/prjct2.png"));
        project.setIcon(e);
    }//GEN-LAST:event_projectMouseEntered

    private void projectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectMouseExited
        ImageIcon g = new ImageIcon(getClass().getResource("/AppPackage/prjct1.png"));
        project.setIcon(g);
    }//GEN-LAST:event_projectMouseExited

    private void projectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectMouseClicked
      AnimationClass Anim = new AnimationClass();
      Anim.jLabelXLeft(840,755,10,1,bymuchwat);
      Anim.jLabelXRight(755,840,10,1,bymuchwat);
    }//GEN-LAST:event_projectMouseClicked

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        AnimationClass Anim = new AnimationClass();
        Anim.jLabelYDown(54,150,10,1,idcard);
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
         AnimationClass Anim = new AnimationClass();
        Anim.jLabelYUp(150,54,10,1,idcard);
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
         AnimationClass Anim = new AnimationClass();
        Anim.jLabelYDown(150,220,13,1,logo);
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
       AnimationClass Anim = new AnimationClass();
        Anim.jLabelYUp(220,150,13,1,logo);
    }//GEN-LAST:event_passwordFocusLost

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String name = username.getText();
        String pass = password.getText();
        if(name.contains("Muchwat") && pass.contains("5512")){
             new StandbyClass().setVisible(true);
             this.setVisible(false);
        }else{     
           AnimationClass Anim = new AnimationClass();
           Anim.jLabelYUp(150,54,10,1,idcard);
           prompt.setText("Wrong Password or Username try again.");
           new StandbyClass().setVisible(false);
           this.setVisible(true);
            
        }
    }//GEN-LAST:event_submitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i=i+0.05){
            String val =i+"F";
            float op = Float.valueOf(val);
            this.setOpacity(op);
            try{
                Thread.sleep(80);
            }
            catch(Exception e){
                
            }      
        }
    }//GEN-LAST:event_formWindowOpened

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
       username.setText(null);
       password.setText(null);
       username.grabFocus();
    }//GEN-LAST:event_resetMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if(show.isSelected() == true){
          password.setEchoChar((char)0);
        }else{        
          password.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Container;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel bymuchwat;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel idcard;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel min;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel project;
    private javax.swing.JLabel prompt;
    private javax.swing.JLabel reset;
    private javax.swing.JCheckBox show;
    private javax.swing.JLabel showpass;
    private javax.swing.JLabel submit;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
